# fly.toml app configuration file generated for stadiumz-generative-api on 2023-11-20T11:37:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stadiumz-generative-api"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
